"""adding the core models

Revision ID: 32c0bd577940
Revises: 
Create Date: 2026-07-01 14:00:23.753327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c0bd577940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chamas',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chama_type', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('default_contribution_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contribution_frequency', sa.String(length=50), nullable=True),
    sa.Column('contribution_due_day', sa.Integer(), nullable=True),
    sa.Column('late_fine_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('late_fine_days_grace', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chama_accounts',
    sa.Column('chama_id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_reconciled_date', sa.DateTime(), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chama_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('last_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chama_id', name='uq_member_profile_user_chama')
    )
    op.create_table('ledger_entries',
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('chama_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('chama_account_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_subtype', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_account_id'], ['chama_accounts.id'], ),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trails',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chama_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('ledger_entry_id', sa.String(length=36), nullable=True),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=255), nullable=True),
    sa.Column('current_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_trails')
    op.drop_table('ledger_entries')
    op.drop_table('member_profiles')
    op.drop_table('chama_accounts')
    op.drop_table('chamas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
