"""adding column is_primary for accounts

Revision ID: 5ae042ae46c2
Revises: 9e5f8c3a7d21
Create Date: 2026-08-13 18:24:21.850589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae042ae46c2'
down_revision = '9e5f8c3a7d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False))
        batch_op.create_index('uq_chama_primary_account', ['chama_id'], unique=True, sqlite_where=sa.text('is_primary = 1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_accounts', schema=None) as batch_op:
        batch_op.drop_index('uq_chama_primary_account', sqlite_where=sa.text('is_primary = 1'))
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
